/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RNcuXE3uG9W
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from '@/components/ui/collapsible'

export function DasL () {
  return (
    <>
      <div className='fixed top-0 left-0 z-50 h-full w-[300px] bg-white shadow-lg transition-transform duration-300 ease-in-out [&[data-state=open]]:translate-x-0 [&[data-state=closed]:-translate-x-full]'>
        <div className='flex h-full flex-col justify-between'>
          <div className='space-y-6 p-6'>
            <div className='flex items-center justify-between'>
              <Link className='flex items-center gap-2 font-semibold' href='#'>
                <Package2Icon className='h-6 w-6' />
                <span>Acme Inc</span>
              </Link>
              <Collapsible>
                <CollapsibleTrigger asChild>
                  <Button className='rounded-full' size='icon' variant='ghost'>
                    <XIcon className='h-5 w-5' />
                    <span className='sr-only'>Close sidebar</span>
                  </Button>
                </CollapsibleTrigger>
                <CollapsibleContent className='absolute top-6 right-6'>
                  <div className='grid gap-2'>
                    <Link
                      className='flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 '
                      href='#'
                    >
                      Workers
                    </Link>
                    <Link
                      className='flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 '
                      href='#'
                    >
                      Detect
                    </Link>
                    <Link
                      className='flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 '
                      href='#'
                    >
                      API Docs
                    </Link>
                  </div>
                </CollapsibleContent>
              </Collapsible>
            </div>
            <nav className='grid gap-2'>
              <Link
                className='flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 '
                href='#'
              >
                <UsersIcon className='h-5 w-5' />
                Workers
              </Link>
              <Link
                className='flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 '
                href='#'
              >
                <EyeIcon className='h-5 w-5' />
                Detect
              </Link>
              <Link
                className='flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 focus:outline-none disabled:pointer-events-none disabled:opacity-50 '
                href='#'
              >
                <BookIcon className='h-5 w-5' />
                API Docs
              </Link>
            </nav>
          </div>
          <div className='border-t px-6 py-4 '>
            <Button className='w-full' variant='outline'>
              Upgrade to Pro
            </Button>
          </div>
        </div>
      </div>
      <Collapsible defaultOpen>
        <CollapsibleTrigger asChild>
          <Button className='fixed top-4 left-4 z-50 rounded-full' size='icon' variant='ghost'>
            <MenuIcon className='h-6 w-6' />
            <span className='sr-only'>Toggle sidebar</span>
          </Button>
        </CollapsibleTrigger>
      </Collapsible>
    </>
  )
}

function BookIcon (props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20' />
    </svg>
  )
}

function EyeIcon (props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z' />
      <circle cx='12' cy='12' r='3' />
    </svg>
  )
}

function MenuIcon (props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <line x1='4' x2='20' y1='12' y2='12' />
      <line x1='4' x2='20' y1='6' y2='6' />
      <line x1='4' x2='20' y1='18' y2='18' />
    </svg>
  )
}

function Package2Icon (props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z' />
      <path d='m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9' />
      <path d='M12 3v6' />
    </svg>
  )
}

function UsersIcon (props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2' />
      <circle cx='9' cy='7' r='4' />
      <path d='M22 21v-2a4 4 0 0 0-3-3.87' />
      <path d='M16 3.13a4 4 0 0 1 0 7.75' />
    </svg>
  )
}

function XIcon (props) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M18 6 6 18' />
      <path d='m6 6 12 12' />
    </svg>
  )
}
